version: '3.8'
services:
  devcontainer:
    build:
      context: ../apps/jupyter
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    # netwrok_mode: 
    command: sleep infinity
  # streamlit:
  #   build:
  #     context: apps/streamlit
  #   volumes:
  #     - ../ ..:/workspaces:cached
  #   # netwrok_mode: 
  #   command: sleep infinity
